#-------------------------------
# Site Settings
title: SANE.digital
logo: '/images/logo2.png'
description: Elevate your tech team.
color_scheme: dark


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Work'
      url: '/work/'
    - title: 'Writing'
      url: '/blog/'
    - title: 'Pages'
      submenu:
      - url: '/contact/'
        title: 'Contact'
      - url: '/elements/'
        title: 'Elements'


#-------------------------------
# Author Settings
author:
  author__name: SANE.digital
  author__bio: "We help technical leaders reclaim their sanity." 
  author__avatar:

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/sanedigital"}
- {icon: "ion-logo-facebook", link: "https://facebook.com/san"}
- {icon: "ion-logo-instagram", link: "https://instagram.com"}
- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-github", link: "https://github.com"}
- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Is managing your tech team driving you <span class='crazy'>insane</span>?
  hero__description: SANE.digital helps technical leaders reclaim their sanity and elevate their team's status within their organization.<br><br>Increase your velocity, improve team morale, and impress your stakeholders in the process.
  hero__image: "/images/hero.png"


#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: "Our team comes from:"

logo__items:
  - name: Google
    link: "https://www.google.com/"
    image: "/images/google.svg"

  - name: Deloitte
    link: "https://www.deloitte.com/"
    image: "/images/deloitte.svg"

  - name: Santander
    link: "https://www.santander.com/"
    image: "/images/santander.svg"

  - name: VISA
    link: "https://www.visa.com/"
    image: "/images/visa.svg"

  - name: Newsweek
    link: "https://www.newsweek.com/"
    image: "/images/newsweek.svg"

  - name: Zipline
    link: "https://www.zipline.com/"
    image: "/images/zipline.svg"

#-------------------------------
# Newsletter
mailchimp:
  enable: false
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text: Your email address...
  mailchimp__button__text: Subscribe


#-------------------------------
# Work Settings
work:
  enable: true
  work__title: Industries
  work__description: We have experience in several industries.


#-------------------------------
# Testimonials Section
testimonials:
  enable: true

testimonial__title: Clients
testimonial__description:

testimonial__items:
  - name: "Hanna Septimus"
    image: "/images/client-1.jpg"
    designation: "Product Designer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Carla Rosser"
    image: "/images/client-2.jpg"
    designation: "Statistician"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Maria Curtis"
    image: "/images/client-3.jpg"
    designation: "Team Lead"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Carter Bergson"
    image: "/images/client-4.jpg"
    designation: "CEO, Founder"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Jordyn Franci"
    image: "/images/client-5.jpg"
    designation: "Personal Trainer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Mira Carder"
    image: "/images/client-6.jpg"
    designation: "Data Scientist"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Madelyn Herwitz"
    image: "/images/client-7.jpg"
    designation: "Frontend Engineer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Anika Schleifer"
    image: "/images/client-8.jpg"
    designation: "Fitness Director"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Wilson Dorwart"
    image: "/images/client-9.jpg"
    designation: "Financial Manager"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"


#-------------------------------
# Blog Section
blog:
  enable: true

blog__settings:
  blog__title: Writing
  blog__description:


#-------------------------------
# Footer Settings
footer__background__image: "/images/bg.jpg"

#-------------------------------
# Contact Settings
contact:
  email: contact@sane.digital
  description: Let's chat.

# NOTE
# Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: G-N18G2SSBGW